name: ssp
channels:
  - conda-forge
dependencies:
  - python=3.12
  - "numpy<2.0"
  - "zarr<3"
  - cmake
  - scipy
  - six
  - cython
  - numba
  - pillow
  - pywavelets
  - astra-toolbox
  - tqdm
  - "setuptools<82"
  - pip
  - wheel
  - pip:
      - bm3d
      - xdesign
      - scikit-image
